#!/usr/bin/env bash
set -euo pipefail

# Bark push helper for cc-notify
# Generated by setup.sh into ~/.local/share/cc-notify/bark-push.sh
#
# Usage:
#   bark-push.sh 'Your message here'        # message as argument
#   echo 'Your message' | bark-push.sh      # message from stdin
#
# Encryption (AES-128-CBC):
#   When ENC_KEY_HEX and ENC_IV_HEX are set, the notification payload is
#   encrypted before sending. The bark-server and APNs only see ciphertext.
#   Configure the same key/IV in the Bark iOS app under Push Encryption.
#
#   To generate a key/IV pair:
#     KEY="$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 16)"
#     IV="$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 16)"
#     printf '%s' "$KEY" | xxd -ps -c 200   # hex for ENC_KEY_HEX
#     printf '%s' "$IV"  | xxd -ps -c 200   # hex for ENC_IV_HEX

DEVICE_KEY='YOUR_DEVICE_KEY'
BASE_URL='https://your-host.ts.net'
ENC_KEY_HEX=''
ENC_IV_HEX=''

body=""
if [[ $# -gt 0 ]]; then
    body="$1"
else
    body="$(cat)"
fi
[[ -z "$body" ]] && exit 0

if [[ -n "$ENC_KEY_HEX" ]]; then
    payload=$(jq -nc --arg t "Claude Code" --arg b "$body" '{"title":$t,"body":$b,"group":"claude"}')
    ciphertext=$(echo -n "$payload" | openssl enc -aes-128-cbc -K "$ENC_KEY_HEX" -iv "$ENC_IV_HEX" | base64 -w 0)
    curl -s -H 'Content-Type: application/json' \
      -d "$(jq -nc --arg dk "$DEVICE_KEY" --arg ct "$ciphertext" '{device_key:$dk,ciphertext:$ct}')" \
      "${BASE_URL}/push"
else
    curl -s -H 'Content-Type: application/json' \
      -d "$(jq -nc --arg dk "$DEVICE_KEY" --arg t "Claude Code" --arg b "$body" '{device_key:$dk,title:$t,body:$b,group:"claude"}')" \
      "${BASE_URL}/push"
fi
